import { describe, expect, it, vi } from "vitest";
import { getBatch, listBatches, type FiscalBatchQueryRepository } from "@/modules/fiscal/application/fiscal-batch-queries";
import type { CommandContext } from "@/shared/application/command-context";
function ctx(role: CommandContext["actorRole"] = "OWNER"): CommandContext { return { tenantId: "tenant-1", actorId: "user-1", actorRole: role, correlationId: "corr-1" }; }
function batch(overrides: Record<string, unknown> = {}) { return { id: "batch-1", tenantId: "tenant-1", status: "SIMULATED", batchNumber: "BATCH-001", createdBy: "user-1", submittedBy: "user-1", submittedAt: new Date("2026-05-01T10:00:00.000Z"), simulatedBy: "user-1", simulatedAt: new Date("2026-05-01T10:10:00.000Z"), approvedBy: null, approvedAt: null, cancelledBy: null, cancelledAt: null, cancelReason: null, totalGrossAmountCents: 15000n, createdAt: new Date("2026-05-01T09:00:00.000Z"), updatedAt: new Date("2026-05-01T10:10:00.000Z"), itemsCount: 1, items: [{ id: "item-1", tenantId: "tenant-1", batchId: "batch-1", candidateId: "candidate-1", status: "INCLUDED", grossAmountCents: 15000n }], ...overrides }; }
function repo(overrides: Partial<FiscalBatchQueryRepository> = {}): FiscalBatchQueryRepository { return { listBatches: vi.fn().mockResolvedValue([batch()]), findBatchDetail: vi.fn().mockResolvedValue(batch()), ...overrides }; }
describe("batches API query contracts", () => {
  it("lists batches with batches.simulate and serializes cents as string", async () => { const repository = repo(); const [item] = await listBatches({ context: ctx("FISCAL_OPERATOR"), repository, status: "SIMULATED" }); expect(repository.listBatches).toHaveBeenCalledWith({ tenantId: "tenant-1", status: "SIMULATED" }); expect(item.totalGrossAmountCents).toBe("15000"); expect(item.items?.[0].grossAmountCents).toBe("15000"); expect(item).not.toHaveProperty("tenantId"); });
  it("blocks read roles without batches.simulate", async () => { await expect(listBatches({ context: ctx("ACCOUNTANT"), repository: repo() })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("rejects cross-tenant batches from repository results", async () => { await expect(listBatches({ context: ctx(), repository: repo({ listBatches: vi.fn().mockResolvedValue([batch({ tenantId: "tenant-2" })]) }) })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("returns detail with allowlisted items", async () => { const detail = await getBatch({ context: ctx(), repository: repo(), batchId: "batch-1" }); expect(detail.items?.[0]).toEqual({ id: "item-1", candidateId: "candidate-1", status: "INCLUDED", grossAmountCents: "15000" }); expect(detail.items?.[0]).not.toHaveProperty("tenantId"); });
});