import { describe, expect, it, vi } from "vitest";
import { getInconsistency, listInconsistencies, type FiscalInconsistencyQueryRepository } from "@/modules/fiscal/application/fiscal-inconsistency-queries";
import type { CommandContext } from "@/shared/application/command-context";
function ctx(role: CommandContext["actorRole"] = "OWNER"): CommandContext { return { tenantId: "tenant-1", actorId: "user-1", actorRole: role, correlationId: "corr-1" }; }
function row(overrides: Record<string, unknown> = {}) { return { id: "inc-1", tenantId: "tenant-1", candidateId: "candidate-1", importBatchId: "import-1", importRowId: "row-1", type: "MISSING_AMOUNT", severity: "BLOCKING", status: "OPEN", message: "Valor ausente", details: { internal: "not-public" }, resolutionNote: null, resolvedBy: null, resolvedAt: null, createdAt: new Date("2026-05-01T10:00:00.000Z"), updatedAt: new Date("2026-05-01T10:10:00.000Z"), ...overrides }; }
function repo(overrides: Partial<FiscalInconsistencyQueryRepository> = {}): FiscalInconsistencyQueryRepository { return { listInconsistencies: vi.fn().mockResolvedValue([row()]), findInconsistencyDetail: vi.fn().mockResolvedValue(row()), ...overrides }; }
describe("inconsistencies API query contracts", () => {
  it("lists inconsistencies with candidates.view and allowlisted DTO", async () => { const repository = repo(); const [item] = await listInconsistencies({ context: ctx("ACCOUNTANT"), repository, status: "OPEN", severity: "BLOCKING" }); expect(repository.listInconsistencies).toHaveBeenCalledWith({ tenantId: "tenant-1", status: "OPEN", severity: "BLOCKING" }); expect(item).toMatchObject({ id: "inc-1", type: "MISSING_AMOUNT", severity: "BLOCKING", status: "OPEN" }); expect(item).not.toHaveProperty("tenantId"); expect(item).not.toHaveProperty("details"); expect(item).not.toHaveProperty("resolvedBy"); });
  it("blocks roles without candidates.view", async () => { await expect(listInconsistencies({ context: ctx("FINANCIAL_OPERATOR"), repository: repo() })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("rejects cross-tenant repository rows", async () => { await expect(listInconsistencies({ context: ctx(), repository: repo({ listInconsistencies: vi.fn().mockResolvedValue([row({ tenantId: "tenant-2" })]) }) })).rejects.toMatchObject({ code: "FORBIDDEN" }); });
  it("returns detail without raw details", async () => { const detail = await getInconsistency({ context: ctx(), repository: repo(), inconsistencyId: "inc-1" }); expect(detail).not.toHaveProperty("details"); expect(detail.resolvedAt).toBeNull(); });
});